<section class="skills" id="skills" data-full-height>
	<article class="about__wrapper">
		<ul class="work__list">
			<h1 class="about__heading">Skills</h1>
			
			<li class="skills__item">
				<div id="Gulp">
				</div>
			</li>

			<li class="skills__item">
				<div id="HTML">
				</div>
			</li>

			<li class="skills__item">
				<div id="CSS">
				</div>
			</li>

			<li class="skills__item">
				<div id="JavaScript">
				</div>
			</li>
		</ul>

	</article>
</section>