<footer class="footer" id="footer" role="footer">
	<div class="u-wrapper">
		<span class="footer__text"><a class="home__link" href="mailto:rohithpalagiri@gmail.com">Want To Chat?</a></span>
		<div class="footer__links">
			<a target="_blank" href="https://github.com/rohithpalagiri" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#github" /></svg></a>
			<a target="_blank" href="https://www.linkedin.com/in/rohith-palagiri-a93ba641?trk=nav_responsive_tab_profile_pic" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#linkedin" /></svg></a>
			<a target="_blank" href="https://twitter.com/RohithP" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#twitter" /></svg></a>
		</div>
	</div>
</footer>